<?php

$tester = "hello";
/*
$song_names = array(
"livin' on a prayer",
"pour some sugar on me",
"hungry like the wolf",
"billie jean",
"when doves cry",
"i can't go for that",
"sweet child o' mine",
"like a virgin",
"walk this way",
"you shook me all night long",
"don't stop believing",
"how will i know",
"with or without you",
"walk like an egyptian",
"jump",
"need you tonight",
"here i go again",
"come on eileen",
"time after time",
"jessie's girl",
"beat it",
"just like heaven",
"girls just want to have fun",
"take on me",
"our lips are sealed",
"welcome to the jungle",
"too shy",
"wake me up before you go-go",
"burning down the house",
"love is a battlefield",
"under pressure",
"sister christian",
"tainted love",
"every rose has it's thorn",
"in the air tonight",
"867-5309/jenny",
"janie's got a gun",
"pride",
"i melt with you",
"love shack",
"dr. feelgood",
"london calling",
"look of love",
"cruel summer",
"nasty",
"every breath you take",
"we're not gonna take it",
"born in the u.s.a.",
"fight for your right",
"sweet dreams",
"round and round",
"you spin me round",
"white wedding",
"push it",
"i ran",
"total eclipse of the heart",
"mickey",
"do you really want to hurt me",
"jack & diane",
"bust a move",
"mr. roboto",
"take my breath away",
"whip it",
"straight up",
"i want to know what love is",
"just can't get enough",
"keep on loving you",
"fight the power",
"it's the end of the world as we know it",
"i love rock n' roll",
"super freak",
"one thing leads to another",
"99 luftballons",
"faith",
"little red corvette",
"she blinded me with science",
"candy girl",
"call me",
"don't you want me?",
"it takes two",
"word up!",
"tempted",
"kiss",
"all night long",
"addicted to love",
"i want candy",
"rock me amadeus",
"ain't nobody",
"brass in pocket",
"wild thing",
"walking on sunshine",
"you got it",
"cars",
"start me up",
"only in my dreams",
"down under",
"what i like about you",
"my perogative",
"everybody have fun tonight",
"working for the weekend");
*/
function get_songs(){
    return array(
"livin' on a prayer",
"pour some sugar on me",
"hungry like the wolf",
"billie jean",
"when doves cry",
"i can't go for that",
"sweet child o' mine",
"like a virgin",
"walk this way",
"you shook me all night long",
"don't stop believing",
"how will i know",
"with or without you",
"walk like an egyptian",
"jump",
"need you tonight",
"here i go again",
"come on eileen",
"time after time",
"jessie's girl",
"beat it",
"just like heaven",
"girls just want to have fun",
"take on me",
"our lips are sealed",
"welcome to the jungle",
"too shy",
"wake me up before you go-go",
"burning down the house",
"love is a battlefield",
"under pressure",
"sister christian",
"tainted love",
"every rose has it's thorn",
"in the air tonight",
"867-5309/jenny",
"janie's got a gun",
"pride",
"i melt with you",
"love shack",
"dr. feelgood",
"london calling",
"look of love",
"cruel summer",
"nasty",
"every breath you take",
"we're not gonna take it",
"born in the u.s.a.",
"fight for your right",
"sweet dreams",
"round and round",
"you spin me round",
"white wedding",
"push it",
"i ran",
"total eclipse of the heart",
"mickey",
"do you really want to hurt me",
"jack & diane",
"bust a move",
"mr. roboto",
"take my breath away",
"whip it",
"straight up",
"i want to know what love is",
"just can't get enough",
"keep on loving you",
"fight the power",
"it's the end of the world as we know it",
"i love rock n' roll",
"super freak",
"one thing leads to another",
"99 luftballons",
"faith",
"little red corvette",
"she blinded me with science",
"candy girl",
"call me",
"don't you want me?",
"it takes two",
"word up!",
"tempted",
"kiss",
"all night long",
"addicted to love",
"i want candy",
"rock me amadeus",
"ain't nobody",
"brass in pocket",
"wild thing",
"walking on sunshine",
"you got it",
"cars",
"start me up",
"only in my dreams",
"down under",
"what i like about you",
"my perogative",
"everybody have fun tonight",
"working for the weekend");
}

?>
